#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM_System_Demo
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="CRMBase")]
	public partial class DataCRMDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insert_user(_user instance);
    partial void Update_user(_user instance);
    partial void Delete_user(_user instance);
    partial void Insert_product(_product instance);
    partial void Update_product(_product instance);
    partial void Delete_product(_product instance);
    partial void Insert_operations_product(_operations_product instance);
    partial void Update_operations_product(_operations_product instance);
    partial void Delete_operations_product(_operations_product instance);
    partial void Insert_customer(_customer instance);
    partial void Update_customer(_customer instance);
    partial void Delete_customer(_customer instance);
    partial void Insert_contract(_contract instance);
    partial void Update_contract(_contract instance);
    partial void Delete_contract(_contract instance);
    #endregion
		
		public DataCRMDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["CRMBaseConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataCRMDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataCRMDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataCRMDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataCRMDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<_user> _users
		{
			get
			{
				return this.GetTable<_user>();
			}
		}
		
		public System.Data.Linq.Table<_product> _products
		{
			get
			{
				return this.GetTable<_product>();
			}
		}
		
		public System.Data.Linq.Table<_operations_product> _operations_products
		{
			get
			{
				return this.GetTable<_operations_product>();
			}
		}
		
		public System.Data.Linq.Table<_customer> _customers
		{
			get
			{
				return this.GetTable<_customer>();
			}
		}
		
		public System.Data.Linq.Table<_contract> _contracts
		{
			get
			{
				return this.GetTable<_contract>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.[_user]")]
	public partial class _user : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _name_and_surname;
		
		private string _login;
		
		private string _password;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void Onname_and_surnameChanging(string value);
    partial void Onname_and_surnameChanged();
    partial void OnloginChanging(string value);
    partial void OnloginChanged();
    partial void OnpasswordChanging(string value);
    partial void OnpasswordChanged();
    #endregion
		
		public _user()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name_and_surname", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string name_and_surname
		{
			get
			{
				return this._name_and_surname;
			}
			set
			{
				if ((this._name_and_surname != value))
				{
					this.Onname_and_surnameChanging(value);
					this.SendPropertyChanging();
					this._name_and_surname = value;
					this.SendPropertyChanged("name_and_surname");
					this.Onname_and_surnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_login", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string login
		{
			get
			{
				return this._login;
			}
			set
			{
				if ((this._login != value))
				{
					this.OnloginChanging(value);
					this.SendPropertyChanging();
					this._login = value;
					this.SendPropertyChanged("login");
					this.OnloginChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_password", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string password
		{
			get
			{
				return this._password;
			}
			set
			{
				if ((this._password != value))
				{
					this.OnpasswordChanging(value);
					this.SendPropertyChanging();
					this._password = value;
					this.SendPropertyChanged("password");
					this.OnpasswordChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.[_product]")]
	public partial class _product : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _name;
		
		private decimal _price_buy;
		
		private decimal _price_sell;
		
		private System.DateTime _date_add;
		
		private int _id_user;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void Onprice_buyChanging(decimal value);
    partial void Onprice_buyChanged();
    partial void Onprice_sellChanging(decimal value);
    partial void Onprice_sellChanged();
    partial void Ondate_addChanging(System.DateTime value);
    partial void Ondate_addChanged();
    partial void Onid_userChanging(int value);
    partial void Onid_userChanged();
    #endregion
		
		public _product()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_price_buy", DbType="Decimal(10,2) NOT NULL")]
		public decimal price_buy
		{
			get
			{
				return this._price_buy;
			}
			set
			{
				if ((this._price_buy != value))
				{
					this.Onprice_buyChanging(value);
					this.SendPropertyChanging();
					this._price_buy = value;
					this.SendPropertyChanged("price_buy");
					this.Onprice_buyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_price_sell", DbType="Decimal(10,2) NOT NULL")]
		public decimal price_sell
		{
			get
			{
				return this._price_sell;
			}
			set
			{
				if ((this._price_sell != value))
				{
					this.Onprice_sellChanging(value);
					this.SendPropertyChanging();
					this._price_sell = value;
					this.SendPropertyChanged("price_sell");
					this.Onprice_sellChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_date_add", DbType="Date NOT NULL")]
		public System.DateTime date_add
		{
			get
			{
				return this._date_add;
			}
			set
			{
				if ((this._date_add != value))
				{
					this.Ondate_addChanging(value);
					this.SendPropertyChanging();
					this._date_add = value;
					this.SendPropertyChanged("date_add");
					this.Ondate_addChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_user", DbType="Int NOT NULL")]
		public int id_user
		{
			get
			{
				return this._id_user;
			}
			set
			{
				if ((this._id_user != value))
				{
					this.Onid_userChanging(value);
					this.SendPropertyChanging();
					this._id_user = value;
					this.SendPropertyChanged("id_user");
					this.Onid_userChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.[_operations_product]")]
	public partial class _operations_product : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private System.DateTime _operation_date;
		
		private string _operation_type;
		
		private decimal _operation_price;
		
		private int _id_user;
		
		private int _id_customer;
		
		private int _id_contract;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void Onoperation_dateChanging(System.DateTime value);
    partial void Onoperation_dateChanged();
    partial void Onoperation_typeChanging(string value);
    partial void Onoperation_typeChanged();
    partial void Onoperation_priceChanging(decimal value);
    partial void Onoperation_priceChanged();
    partial void Onid_userChanging(int value);
    partial void Onid_userChanged();
    partial void Onid_customerChanging(int value);
    partial void Onid_customerChanged();
    partial void Onid_contractChanging(int value);
    partial void Onid_contractChanged();
    #endregion
		
		public _operations_product()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_operation_date", DbType="Date NOT NULL")]
		public System.DateTime operation_date
		{
			get
			{
				return this._operation_date;
			}
			set
			{
				if ((this._operation_date != value))
				{
					this.Onoperation_dateChanging(value);
					this.SendPropertyChanging();
					this._operation_date = value;
					this.SendPropertyChanged("operation_date");
					this.Onoperation_dateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_operation_type", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string operation_type
		{
			get
			{
				return this._operation_type;
			}
			set
			{
				if ((this._operation_type != value))
				{
					this.Onoperation_typeChanging(value);
					this.SendPropertyChanging();
					this._operation_type = value;
					this.SendPropertyChanged("operation_type");
					this.Onoperation_typeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_operation_price", DbType="Decimal(10,2) NOT NULL")]
		public decimal operation_price
		{
			get
			{
				return this._operation_price;
			}
			set
			{
				if ((this._operation_price != value))
				{
					this.Onoperation_priceChanging(value);
					this.SendPropertyChanging();
					this._operation_price = value;
					this.SendPropertyChanged("operation_price");
					this.Onoperation_priceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_user", DbType="Int NOT NULL")]
		public int id_user
		{
			get
			{
				return this._id_user;
			}
			set
			{
				if ((this._id_user != value))
				{
					this.Onid_userChanging(value);
					this.SendPropertyChanging();
					this._id_user = value;
					this.SendPropertyChanged("id_user");
					this.Onid_userChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_customer", DbType="Int NOT NULL")]
		public int id_customer
		{
			get
			{
				return this._id_customer;
			}
			set
			{
				if ((this._id_customer != value))
				{
					this.Onid_customerChanging(value);
					this.SendPropertyChanging();
					this._id_customer = value;
					this.SendPropertyChanged("id_customer");
					this.Onid_customerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_contract", DbType="Int NOT NULL")]
		public int id_contract
		{
			get
			{
				return this._id_contract;
			}
			set
			{
				if ((this._id_contract != value))
				{
					this.Onid_contractChanging(value);
					this.SendPropertyChanging();
					this._id_contract = value;
					this.SendPropertyChanged("id_contract");
					this.Onid_contractChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.[_customer]")]
	public partial class _customer : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _company;
		
		private string _address;
		
		private int _phonenumber;
		
		private int _edrpou;
		
		private int _inn;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OncompanyChanging(string value);
    partial void OncompanyChanged();
    partial void OnaddressChanging(string value);
    partial void OnaddressChanged();
    partial void OnphonenumberChanging(int value);
    partial void OnphonenumberChanged();
    partial void OnedrpouChanging(int value);
    partial void OnedrpouChanged();
    partial void OninnChanging(int value);
    partial void OninnChanged();
    #endregion
		
		public _customer()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_company", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string company
		{
			get
			{
				return this._company;
			}
			set
			{
				if ((this._company != value))
				{
					this.OncompanyChanging(value);
					this.SendPropertyChanging();
					this._company = value;
					this.SendPropertyChanged("company");
					this.OncompanyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_address", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string address
		{
			get
			{
				return this._address;
			}
			set
			{
				if ((this._address != value))
				{
					this.OnaddressChanging(value);
					this.SendPropertyChanging();
					this._address = value;
					this.SendPropertyChanged("address");
					this.OnaddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_phonenumber", DbType="Int NOT NULL")]
		public int phonenumber
		{
			get
			{
				return this._phonenumber;
			}
			set
			{
				if ((this._phonenumber != value))
				{
					this.OnphonenumberChanging(value);
					this.SendPropertyChanging();
					this._phonenumber = value;
					this.SendPropertyChanged("phonenumber");
					this.OnphonenumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_edrpou", DbType="Int NOT NULL")]
		public int edrpou
		{
			get
			{
				return this._edrpou;
			}
			set
			{
				if ((this._edrpou != value))
				{
					this.OnedrpouChanging(value);
					this.SendPropertyChanging();
					this._edrpou = value;
					this.SendPropertyChanged("edrpou");
					this.OnedrpouChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_inn", DbType="Int NOT NULL")]
		public int inn
		{
			get
			{
				return this._inn;
			}
			set
			{
				if ((this._inn != value))
				{
					this.OninnChanging(value);
					this.SendPropertyChanging();
					this._inn = value;
					this.SendPropertyChanged("inn");
					this.OninnChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.[_contract]")]
	public partial class _contract : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private System.DateTime _date_conclusion;
		
		private decimal _total_price;
		
		private decimal _contract_balance;
		
		private System.DateTime _date_end;
		
		private int _id_customer;
		
		private string _contract_type;
		
		private int _id_product;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void Ondate_conclusionChanging(System.DateTime value);
    partial void Ondate_conclusionChanged();
    partial void Ontotal_priceChanging(decimal value);
    partial void Ontotal_priceChanged();
    partial void Oncontract_balanceChanging(decimal value);
    partial void Oncontract_balanceChanged();
    partial void Ondate_endChanging(System.DateTime value);
    partial void Ondate_endChanged();
    partial void Onid_customerChanging(int value);
    partial void Onid_customerChanged();
    partial void Oncontract_typeChanging(string value);
    partial void Oncontract_typeChanged();
    partial void Onid_productChanging(int value);
    partial void Onid_productChanged();
    #endregion
		
		public _contract()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_date_conclusion", DbType="Date NOT NULL")]
		public System.DateTime date_conclusion
		{
			get
			{
				return this._date_conclusion;
			}
			set
			{
				if ((this._date_conclusion != value))
				{
					this.Ondate_conclusionChanging(value);
					this.SendPropertyChanging();
					this._date_conclusion = value;
					this.SendPropertyChanged("date_conclusion");
					this.Ondate_conclusionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_total_price", DbType="Decimal(10,2) NOT NULL")]
		public decimal total_price
		{
			get
			{
				return this._total_price;
			}
			set
			{
				if ((this._total_price != value))
				{
					this.Ontotal_priceChanging(value);
					this.SendPropertyChanging();
					this._total_price = value;
					this.SendPropertyChanged("total_price");
					this.Ontotal_priceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_contract_balance", DbType="Decimal(10,2) NOT NULL")]
		public decimal contract_balance
		{
			get
			{
				return this._contract_balance;
			}
			set
			{
				if ((this._contract_balance != value))
				{
					this.Oncontract_balanceChanging(value);
					this.SendPropertyChanging();
					this._contract_balance = value;
					this.SendPropertyChanged("contract_balance");
					this.Oncontract_balanceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_date_end", DbType="Date NOT NULL")]
		public System.DateTime date_end
		{
			get
			{
				return this._date_end;
			}
			set
			{
				if ((this._date_end != value))
				{
					this.Ondate_endChanging(value);
					this.SendPropertyChanging();
					this._date_end = value;
					this.SendPropertyChanged("date_end");
					this.Ondate_endChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_customer", DbType="Int NOT NULL")]
		public int id_customer
		{
			get
			{
				return this._id_customer;
			}
			set
			{
				if ((this._id_customer != value))
				{
					this.Onid_customerChanging(value);
					this.SendPropertyChanging();
					this._id_customer = value;
					this.SendPropertyChanged("id_customer");
					this.Onid_customerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_contract_type", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string contract_type
		{
			get
			{
				return this._contract_type;
			}
			set
			{
				if ((this._contract_type != value))
				{
					this.Oncontract_typeChanging(value);
					this.SendPropertyChanging();
					this._contract_type = value;
					this.SendPropertyChanged("contract_type");
					this.Oncontract_typeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_product", DbType="Int NOT NULL")]
		public int id_product
		{
			get
			{
				return this._id_product;
			}
			set
			{
				if ((this._id_product != value))
				{
					this.Onid_productChanging(value);
					this.SendPropertyChanging();
					this._id_product = value;
					this.SendPropertyChanged("id_product");
					this.Onid_productChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
